msrv = "1.88.0"
module-items-ordered-within-groupings = "all"
module-item-order-groupings = [
  [
    "macro",
    [
      "macro",
    ],
  ],
  [
    "modules",
    [
      "extern_crate",
      "mod",
      "foreign_mod",
    ],
  ],
  [
    "use",
    [
      "use",
    ],
  ],
  [
    "global_asm",
    [
      "global_asm",
    ],
  ],
  [
    "statics",
    [
      "static",
    ],
  ],
  [
    "consts",
    [
      "const",
    ],
  ],
  [
    "ty_aliases",
    [
      "ty_alias",
    ],
  ],
  [
    "enums",
    [
      "enum",
    ],
  ],
  [
    "structs",
    [
      "struct",
    ],
  ],
  [
    "unions",
    [
      "union",
    ],
  ],
  [
    "traits",
    [
      "trait",
      "trait_alias",
    ],
  ],
  [
    "impls",
    [
      "impl",
    ],
  ],
  [
    "fns",
    [
      "fn",
    ],
  ],
]
source-item-ordering = ["module", "struct", "trait"]
