[package]
authors = ["gamma0987 <gamma0987@posteo.de>"]
name = "gungraun-summary"
categories = ["data-structures", "parser-implementations"]
edition.workspace = true
homepage.workspace = true
keywords = ["gungraun", "summary", "json", "serde", "schema"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "6.0.0"
description = """
Typed Rust data model and parsing helpers for Gungraun summary JSON files
"""
readme = "README.md"

[features]
schema = ["gungraun-runner/schema", "dep:schemars"]

[dependencies]
either-or-both = { workspace = true }
gungraun-runner = { path = "../gungraun-runner", version = ">=0.19.3", default-features = false, features = [
  "summary",
] }
indexmap = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions.workspace = true

[[bin]]
name = "gungraun-summary-schemagen"
path = "src/main.rs"
required-features = ["schema"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
