[package]
authors = ["gamma0987 <gamma0987@posteo.de>"]
categories.workspace = true
description = """
High-precision, one-shot and consistent benchmarking framework/harness for Rust. \
All Valgrind tools at your fingertips.
"""
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "gungraun-common"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[lib]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
strum = ["dep:strum"]

[dependencies]
strum = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
