[tool.bumpversion]
current_version = "0.6.1"
commit = true
message = "Bump gungraun-macros version v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "gungraun-macros/Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "gungraun/Cargo.toml"
search = "gungraun-macros = {{ path = \"../gungraun-macros\", version = \"={current_version}\""
replace = "gungraun-macros = {{ path = \"../gungraun-macros\", version = \"={new_version}\""
