[tool.bumpversion]
commit = true
current_version = "1.67.1"
message = "Bump MSRV v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = "rust-version = \"{current_version}\""
replace = "rust-version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "Justfile"
search = "msrv := '{current_version}'"
replace = "msrv := '{new_version}'"

[[tool.bumpversion.files]]
filename = ".github/workflows/cicd.yml"

[[tool.bumpversion.files]]
filename = "README.md"

[[tool.bumpversion.files]]
filename = "iai-callgrind-macros/README.md"

[[tool.bumpversion.files]]
filename = "iai-callgrind-runner/README.md"

[[tool.bumpversion.files]]
filename = ".clippy.toml"

[[tool.bumpversion.files]]
filename = "CONTRIBUTING.md"
search = "Rust `{current_version}`"
replace = "Rust `{new_version}`"
