[tool.bumpversion]
current_version = "7"
commit = false
parse = "(?P<major>\\d+)"
serialize = ["{major}"]

[[tool.bumpversion.files]]
filename = "crates/gungraun-runner/src/summary/model.rs"
search = "const SCHEMA_VERSION: &str = \"{current_version}\";"
replace = "const SCHEMA_VERSION: &str = \"{new_version}\";"

[[tool.bumpversion.files]]
filename = "crates/gungraun-tests/src/bench.rs"
search = "const SCHEMA_VERSION: &str = \"{current_version}\";"
replace = "const SCHEMA_VERSION: &str = \"{new_version}\";"
