[tool.bumpversion]
current_version = "6"
commit = false
parse = "(?P<major>\\d+)"
serialize = ["{major}"]

[[tool.bumpversion.files]]
filename = "gungraun-runner/src/runner/summary.rs"
search = "const SCHEMA_VERSION: &str = \"{current_version}\";"
replace = "const SCHEMA_VERSION: &str = \"{new_version}\";"

[[tool.bumpversion.files]]
filename = "benchmark-tests/src/bench.rs"
search = "const SCHEMA_VERSION: &str = \"{current_version}\";"
replace = "const SCHEMA_VERSION: &str = \"{new_version}\";"
