[tool.bumpversion]
current_version = "0.19.4"
commit = true
message = "Bump version v{current_version} -> v{new_version}"

# The guide in `docs/src `is not updated here but instead in the Justfile with
# `just bump`

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "crates/gungraun/Cargo.toml"
search = 'path = "../gungraun-runner", version = "={current_version}"'
replace = 'path = "../gungraun-runner", version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "crates/gungraun/src/__internal/mod.rs"
search = "const LIBRARY_VERSION: &str = \"{current_version}\""
replace = "const LIBRARY_VERSION: &str = \"{new_version}\""
