[tool.bumpversion]
current_version = "0.16.1"
commit = true
message = "Bump version v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "gungraun/Cargo.toml"
search = 'path = "../gungraun-runner", version = "={current_version}"'
replace = 'path = "../gungraun-runner", version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "schema-gen/Cargo.toml"
search = 'path = "../gungraun-runner", version = "={current_version}"'
replace = 'path = "../gungraun-runner", version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "gungraun/src/__internal/mod.rs"
search = "const LIBRARY_VERSION: &str = \"{current_version}\""
replace = "const LIBRARY_VERSION: &str = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "gungraun/src/client_requests/mod.rs"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "client-request-tests/Cargo.toml"
search = "version = \"={current_version}\""
replace = "version = \"={new_version}\""
