[package]
authors = [
  "Joining7943 <joining@poSTeo.de>",
  "gamma0987 <gamma0987@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
categories.workspace = true
description = """
High-precision, one-shot and consistent benchmarking framework/harness for Rust. \
All Valgrind tools at your fingertips.
"""
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "gungraun"
readme = "../README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
__ui_tests = ["perf"]
act = ["stubs", "valgrind-requests/act", "perf"]
benchmark = [
  "perf",
  "dep:bincode-next",
  "dep:gungraun-macros",
  "dep:derive_more",
  "dep:gungraun-common",
]
cachegrind = ["gungraun-macros/cachegrind", "act"]
default = ["benchmark"]
perf = ["perf_stubs"]
perf_stubs = ["gungraun-runner/api"]
stubs = ["valgrind-requests/stubs", "dep:cty", "perf_stubs"]

[package.metadata.docs.rs]
features = ["stubs", "perf"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bincode-next = { workspace = true, optional = true }
cty = { workspace = true, optional = true }
# We use the `derive_more` crate anyway in `gungraun-macros`, so there's no
# harm in using it for this small AsRef derive macro
derive_more = { workspace = true, default-features = false, features = [
  "as_ref",
], optional = true }
gungraun-common = { path = "../gungraun-common/", version = "0.1.0", optional = true }
gungraun-macros = { path = "../gungraun-macros", version = "=0.9.1", optional = true }
gungraun-runner = { path = "../gungraun-runner", version = "=0.19.4", default-features = false, features = [
  "api",
], optional = true }
valgrind-requests = { path = "../valgrind-requests", version = "1", optional = true, default-features = false }

[dev-dependencies]
fs_extra = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
trybuild = { workspace = true }

[lints]
workspace = true
