[package]
authors = ["gamma0987 <gamma0987@posteo.de>"]
categories = [
  "api-bindings",
  "development-tools::profiling",
  "development-tools::testing",
  "no-std",
]
description = """
Idiomatic Rust bindings for Valgrind client requests, with zero-indirection \
execution and zero-cost fallback
"""
edition.workspace = true
homepage.workspace = true
keywords = ["valgrind", "bindings", "client-requests", "no_std", "callgrind"]
license.workspace = true
name = "valgrind-requests"
repository.workspace = true
rust-version.workspace = true
version = "1.1.0"

[features]
act = ["stubs"]
alloc = []
default = ["act", "std"]
std = ["alloc"]
stubs = [
  "dep:bindgen",
  "dep:cc",
  "dep:cfg-if",
  "dep:cty",
  "dep:gungraun-common",
  "dep:regex",
  "dep:rustc_version",
  "dep:strum",
]

[package.metadata.docs.rs]
features = ["act"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cfg-if = { workspace = true, optional = true }
cty = { workspace = true, optional = true }

[build-dependencies]
bindgen = { workspace = true, optional = true }
cc = { workspace = true, optional = true }
gungraun-common = { path = "../gungraun-common", version = "=0.1.0", optional = true }
regex = { workspace = true, optional = true }
rustc_version = { workspace = true, optional = true }
strum = { workspace = true, optional = true, features = ["derive"] }

# There are overrides in lib.rs
[lints]
workspace = true
