[book]
authors = ["gamma0987"]
language = "en"
title = "Gungraun Guide"
description = "Gungraun, a high-precision, one-shot and consistent benchmarking framework for Rust"

[rust]
edition = "2024"

[build]
build-dir = "book/0.20.0"

[output.html]
git-repository-url = "https://github.com/gungraun/gungraun"
edit-url-template = "https://github.com/gungraun/gungraun/blob/main/docs/{path}"
additional-css = ["css/my.css", "css/dropdown.css"]
additional-js = ["js/dropdown.js"]
site-url = "/gungraun/"

# https://github.com/marxin/mdbook-linkcheck2
# fork of https://github.com/Michael-F-Bryan/mdbook-linkcheck
[output.linkcheck2]
follow-web-links = true
traverse-parent-directories = true
warning-policy = "error"
exclude = ['https://sourceware.org/git/.*', 'https://repology.org/']
