[package]
authors = ["Joining7943 <joining@posteo.de>", "gamma0987 <gamma0987@posteo.de>"]
categories.workspace = true
description = """
Proc macros for Gungraun: A high-precision, one-shot and consistent benchmarking \
framework/harness for Rust.
"""
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "gungraun-macros"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.9.1"

[features]
cachegrind = []

[lib]
proc-macro = true

[build-dependencies]
rustc_version = { workspace = true }

[dependencies]
derive_more = { workspace = true, default-features = false, features = [
  "deref",
  "deref_mut",
] }
proc-macro-error3 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
