# spell-checker:ignore taiki rustfmt binstall clippy taplo rustup nocapture
# spell-checker:ignore nofile gnuabi armv gnueabi mipsel vmactions usesh proto
# spell-checker:ignore tlsv connrefused copyback toolsdirectory ghcup rustdocflags
# spell-checker:ignore androideabi binutils

name: Build and Check

on:
  push:
    branches: ["main", "cicd", "release", "develop", "[0-9]+-*"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "00 01 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  config:
    name: Shared workflow config
    runs-on: ubuntu-latest
    outputs:
      cargo_term_color: ${{ steps.config.outputs.cargo_term_color }}
      rust_backtrace: ${{ steps.config.outputs.rust_backtrace }}
      valgrind_version: ${{ steps.config.outputs.valgrind_version }}
    steps:
      - id: config
        run: |
          {
            echo 'cargo_term_color=always'
            echo 'rust_backtrace=1'
            echo 'valgrind_version=3.27.0'
          } >> "$GITHUB_OUTPUT"

  basic:
    name: Basic checks
    needs: [config]
    uses: ./.github/workflows/basic.yml
    with:
      cargo_term_color: ${{ needs.config.outputs.cargo_term_color }}
      rust_backtrace: ${{ needs.config.outputs.rust_backtrace }}

  common:
    name: Common checks
    needs: [basic, config]
    uses: ./.github/workflows/common.yml
    with:
      cargo_term_color: ${{ needs.config.outputs.cargo_term_color }}
      valgrind_version: ${{ needs.config.outputs.valgrind_version }}

  valgrind_requests:
    name: Valgrind requests checks
    needs: [basic, config]
    uses: ./.github/workflows/valgrind_requests.yml
    with:
      cargo_term_color: ${{ needs.config.outputs.cargo_term_color }}
      valgrind_version: ${{ needs.config.outputs.valgrind_version }}

  linux:
    name: Linux checks
    needs: [basic, config]
    uses: ./.github/workflows/linux.yml
    with:
      cargo_term_color: ${{ needs.config.outputs.cargo_term_color }}
      valgrind_version: ${{ needs.config.outputs.valgrind_version }}

  freebsd:
    name: Freebsd checks
    needs: [basic, config]
    uses: ./.github/workflows/freebsd.yml
    with:
      cargo_term_color: ${{ needs.config.outputs.cargo_term_color }}

  macos:
    name: MacOS checks
    needs: [basic]
    uses: ./.github/workflows/macos.yml
