# spell-checker:ignore taiki rustfmt binstall clippy taplo rustup nocapture
# spell-checker:ignore nofile gnuabi armv gnueabi mipsel vmactions usesh proto
# spell-checker:ignore tlsv connrefused copyback toolsdirectory ghcup rustdocflags
# spell-checker:ignore androideabi binutils

name: Build and Check

on:
  push:
    branches: ["main", "cicd", "release", "develop", "[0-9]+-*"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "00 01 * * *"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  VALGRIND_VERSION: "3.26.0"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  basic:
    name: Basic checks
    uses: ./.github/workflows/basic.yml

  common:
    name: Common checks
    needs: [basic]
    uses: ./.github/workflows/common.yml

  linux:
    name: Linux checks
    needs: [basic]
    uses: ./.github/workflows/linux.yml

  freebsd:
    name: Freebsd checks
    needs: [basic]
    uses: ./.github/workflows/freebsd.yml

  macos:
    name: MacOS checks
    needs: [basic]
    uses: ./.github/workflows/macos.yml
