# spell-checker:ignore rustdocflags androideabi binutils
name: Common checks

on:
  workflow_call:
    inputs:
      cargo_term_color:
        required: false
        type: string
      valgrind_version:
        required: false
        type: string

env:
  CARGO_TERM_COLOR: ${{ inputs.cargo_term_color }}
  VALGRIND_VERSION: ${{ inputs.valgrind_version }}

jobs:
  schema:
    name: Check gungraun json schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@just
      - name: Check summary.json schema is up-to-date
        run: just schema-gen-diff

  docs:
    name: Docs/ubuntu-latest
    runs-on: ubuntu-latest
    env:
      DOCS_RS: "1"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      # This is important for docs.rs which doesn't have the headers installed
      - name: Try build gungraun without valgrind headers
        run: cargo build --package gungraun --features client_requests_defs --release
      - name: Run doc tests
        run: cargo test --all-features --doc
      - name: Check docs.rs build for gungraun
        run: cargo rustdoc -p gungraun --all-features --config 'build.rustdocflags=["--cfg", "docsrs"]' -- --deny warnings
      - name: Check docs.rs build for gungraun-runner
        run: cargo rustdoc -p gungraun-runner --all-features --config 'build.rustdocflags=["--cfg", "docsrs"]' -- --deny warnings
      - name: Check docs.rs build for gungraun-macros
        run: cargo rustdoc -p gungraun-macros --all-features --config 'build.rustdocflags=["--cfg", "docsrs"]' -- --deny warnings
      - name: Check Documentation
        run: cargo doc --all-features --no-deps --document-private-items

  build_release:
    name: Release build for targets supported by valgrind
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - aarch64-linux-android
          - i686-linux-android
          - armv7-linux-androideabi
          - x86_64-linux-android
          - x86_64-unknown-freebsd
          - i686-unknown-freebsd
        include:
          - cargo: cross
          - needs_ndk: false
          - target: armv7-linux-androideabi
            cargo: cargo
            needs_ndk: true
          - target: aarch64-linux-android
            cargo: cargo
            needs_ndk: true
          - target: i686-linux-android
            cargo: cargo
            needs_ndk: true
          - target: x86_64-linux-android
            cargo: cargo
            needs_ndk: true
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cross
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - name: Install valgrind
        run: ./scripts/install_valgrind.sh "$VALGRIND_VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Cleanup Cross.toml
        run: |
          [[ -e Cross.toml ]] && mv Cross.toml Cross.toml.old || true
      # https://developer.android.com/ndk/guides/other_build_systems
      - name: Use NDK and install cargo config
        if: matrix.needs_ndk
        run: |
          set -x

          min_sdk="21"
          if [[ "${{ matrix.target }}" == "armv7-linux-androideabi" ]]; then
            # binutils_prefix="arm-linux-androideabi"
            compiler_prefix="armv7a-linux-androideabi"
          else
            # binutils_prefix="${{ matrix.target }}"
            compiler_prefix="${{ matrix.target }}"
          fi

          linker="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/${compiler_prefix}${min_sdk}-clang"

          cat <<EOF >~/.cargo/config
          [target.${{ matrix.target }}]
          linker = "$linker"
          EOF
      - name: Update dependencies
        run: cargo update
      - name: Build
        run: |
          cmd=(${{ matrix.cargo }} build --target ${{ matrix.target }} --release)

          set -x
          "${cmd[@]}" --package gungraun-macros
          "${cmd[@]}" --package gungraun
          for feature in default api schema; do
            "${cmd[@]}" --package gungraun-runner --features "$feature"
          done
