name: github pages

on:
  push:
    branches:
      - mdbook
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-binstall
      - uses: taiki-e/install-action@just

      - name: Install mdbook
        run: just args="--no-confirm" book-install

      - name: Clean the book if already present
        run: just book-clean

      - name: Build the book
        run: just book-build

      - name: Test the book
        run: just book-tests

      - name: Cleanup test artifacts
        run: cargo clean

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/mdbook' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          keep_files: true

      # On the gh-pages branch the root is the content of docs/book
      - name: Create/Overwrite link to latest on gh-pages branch
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/mdbook' }}
        run: |
          git config user.email "bot@publish_book"
          git config user.name "bot@publish_book"

          git fetch origin
          git worktree add ../gh-pages gh-pages
          cd ../gh-pages

          latest=$(find -maxdepth 1 -type d -printf '%f\n' | grep -E '^[0-9]+.*$' | sort -V | tail -1)
          rm -rf ./latest
          ln -s "$latest" latest
          git add .

          if ! git status -uno | grep 'nothing to commit'; then
            git commit -m "docs(book): Create link to latest version ${latest}"
            git push
          fi
