name: Deploy iai-callgrind and iai-callgrind-runner
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish iai-callgrind-runner
        run: cargo publish -p iai-callgrind-runner --token ${{ secrets.CRATES_GITHUB_TOKEN }}
      - name: Publish iai-callgrind
        run: cargo publish -p iai-callgrind --token ${{ secrets.CRATES_GITHUB_TOKEN }}
