name: Deploy gungraun and gungraun-runner
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish gungraun-runner
        run: cargo publish -p gungraun-runner --token ${{ secrets.CRATES_GITHUB_TOKEN }}
      - name: Publish gungraun
        run: cargo publish -p gungraun --token ${{ secrets.CRATES_GITHUB_TOKEN }}
