name: github pages

on:
  push:
    branches:
      - mdbook
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  changes:
    runs-on: ubuntu-26.04
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      force: ${{ steps.tag-check.outputs.force }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - '.github/workflows/publish_book.yml'
      - id: tag-check
        run: |
          case "${{ github.ref }}" in
            refs/tags/*) echo "force=true" >> "$GITHUB_OUTPUT" ;;
            refs/heads/mdbook) echo "force=true" >> "$GITHUB_OUTPUT" ;;
            *)            echo "force=false" >> "$GITHUB_OUTPUT" ;;
          esac

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.force == 'true' || needs.changes.outputs.docs == 'true' }}
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-binstall
      - uses: taiki-e/install-action@just

      - name: Delay book build and wait for docs.rs to finish
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )

          counter=0
          max=1800
          echo "Waiting for docs.rs to build docs for gungraun v${version}"
          while true; do
            # The trailing slash is important. Without it the status code is 302
            if curl -s -w '%{http_code}' -o /dev/null "https://docs.rs/gungraun/${version}/gungraun/" | grep -q 200; then
              echo "Docs.rs documentation is online. Continue..."
              break
            elif ((counter > max)); then
              echo "Timeout reached. Aborting..."
              exit 1
            else
              if ((counter == 0)); then
                # Give docs.rs some reasonable head start
                sleep 300
              else
                sleep 1
              fi

              counter=$((counter + 1))
              echo '.'
            fi
          done
      - name: Install mdbook
        run: just book-install --no-confirm

      - name: Clean the book if already present
        run: just book-clean

      - name: Build the book
        run: just book-build

      - name: Test the book
        run: just book-tests

      - name: Cleanup test artifacts
        run: cargo clean

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/mdbook' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          keep_files: true

      # On the gh-pages branch the root is the content of docs/book
      - name: Create/Overwrite link to latest on gh-pages branch
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/mdbook' }}
        run: |
          git config user.email "bot@publish_book"
          git config user.name "bot@publish_book"

          git fetch origin
          git worktree add ../gh-pages gh-pages
          cd ../gh-pages

          latest=$(find . -maxdepth 1 -type d -printf '%f\n' | grep -E '^[0-9]+.*$' | sort -V | tail -1)
          rm -rf ./latest
          ln -s "$latest" latest
          git add .

          if ! git status -uno | grep 'nothing to commit'; then
            git commit -m "docs(book): Create link to latest version ${latest}"
            git push
          fi
